title: Cardano
email: cardano@iohk.io
description: SL Documentation
baseurl: ""
url: "https://cardanodocs.com"
include: ["_pages","_docs"]
permalink: /:title

markdown: kramdown
highlighter: rouge
array: []

theme: jekyll-theme-slate